title: Documentos e Regras do grupo PHP Brasil
url: "http://php-brasil.github.io"
baseurl: "/Documentos"
lang: pt_BR

# Build settings
markdown: kramdown
permalink: /date/
sass:
    style: compressed
